DevMode: true
Debug: true
Symlink: true
SSL: true
Decrypt:
    state:  false
    salt: '42'
    securecode: false

Crypto:
    salt: "AES-128-CBC"
    pepper: "0x42"
    passphrase: "/\/\A$T3R<>FTHEU/\/iV3R$3"

Local: de_DE

Assembly:
    projectCtrl:            ".\Cimply\App\Projects\%project%\controller"
    baseCtrl:               ".\Cimply\App\Base"
    
App:
    baseUrl:                false
    baseName:               "cimply"
    index:                  "index"
    project:                "Console"
    projectPath:            "<?=__DIR__?>"
    namespace:              "Cimply\App\Projects\%project%\App"
    database:               "prod"
    assets:					"assets"
    commonDir:		        "common"
    cacheDir:               "<?=__DIR__?>\Cache"
    debugMode:              true

System:
    useTemplateFor:         [html,css,js,htc]
    useParseFiles:          []
    useNotTranslationFor:   [application/json]
    useNotCachingFor:       [application/json]

Collections:
    
Themes:
    Awesome:	"Font-Awesome"
    Bootstrap:	"Bootstrap"
