DevMode: true
Debug: true
Symlink: true
SSL: true
Decrypt:
    state:  false
    salt: '42'
    securecode: false

Crypto:
    salt: "AES-128-CBC"
    pepper: "0x42"
    passphrase: "/\/\A$T3R<>FTHEU/\/iV3R$3"

Local: de_DE

Assembly:
    projectCtrl:            ".\cimply\app\projects\%project%\controller"
    baseCtrl:               ".\cimply\app\base"
    
App:
    baseUrl:                "/"
    baseName:               "Cimply"
    baseDir:                "/"
    index:                  "index"
    project:                "defaultApp"
    projectPath:            "<?=__DIR__?>"
    namespace:              "cimply\app\projects\%project%\app"
    database:               "prod"
    assets:                 "assets"
    commonDir:		        "common"
    cacheDir:               "cache"
    debugMode:              true

System:
    useTemplateFor:         [html,css,js,htc]
    useParseFiles:          []
    useNotTranslationFor:   [application/json]
    useNotCachingFor:       [application/json]

Collections:
    
Themes:

DBConnect: